SECRET_KEY = "CHANGE_ME"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_HOURS = 2
#newly added for api config
USER_REQUEST_LIMIT = 3
API_KEY_REQUEST_LIMIT = 4
IP_REQUEST_LIMIT = 5

RATE_WINDOW_MINUTES = 1

MAX_IPS_PER_USER = 5
IP_ROTATION_WINDOW_MINUTES = 10
#payment details
PAYMENT_GATEWAY = "MANUAL"

PREMIUM_MONTHLY_AMOUNT = 299
PREMIUM_YEARLY_AMOUNT = 2999

ORDER_ID_PREFIX = "ORD"

PAYMENT_STATUS_CREATED = "CREATED"
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_SUCCESS = "SUCCESS"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_TIMEOUT = "TIMEOUT"

PAYMENT_METHOD_CARD = "CARD"

SUBSCRIPTION_FREE = "FREE"
SUBSCRIPTION_PREMIUM = "PREMIUM"
PLAN_PRICES = {
    "PREMIUM": {
        "MONTHLY": 299,
        "YEARLY": 2999
    }
}

PAYMENT_GATEWAY_TIMEOUT = 300
MAX_PAYMENT_RETRIES = 3